//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public System.Guid Id { get; set; }
        public int NroFactura { get; set; }
        public Nullable<System.Guid> ObraSocial { get; set; }
        public Nullable<System.Guid> Paciente { get; set; }
        public System.Guid Estado { get; set; }
        public string Tipo { get; set; }
    
        public virtual ObraSocial ObraSocial1 { get; set; }
        public virtual Paciente Paciente1 { get; set; }
    }
}
