//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public System.Guid Id { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.Guid Atencion { get; set; }
    
        public virtual AtencionCabecera AtencionCabecera { get; set; }
    }
}
