//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public System.Guid Id { get; set; }
        public System.DateTime FechaCreac { get; set; }
        public string Descripcion { get; set; }
        public string ClaveContable { get; set; }
        public System.Guid CtaCorriente { get; set; }
        public Nullable<System.Guid> MetodoPago { get; set; }
    
        public virtual CtaCorriente CtaCorriente1 { get; set; }
        public virtual MetodoPago MetodoPago1 { get; set; }
    }
}
